### ISSUE TITLE
Hello Ghost

### ISSUE THREAD

**Issue by StdGit** [shawnthompson/resume#2]
Hi Shawn, something for your official teams.

And if you still use email, you can give me one.

Hope you're going well.

---

It appears that the errors detected by the Firefox add-on are within a chat widget that does not properly load when evaluating the page using our online WAVE service. Some dynamic, JavaScript-enabled content may not be loaded in pages when viewed in our online service. The extension can provide an analysis of the more complete content in this case.

I’m not finding the contrast error on the contact page. If you can please let me know which page element it is, then I’ll certainly look into it. 

Thanks,

Jared Smith
WebAIM

Sent from the WebAIM website at 1:52 PM, July 21st, 2021 by Stéphane Ducharme <Stephane.Ducharme@hrsdc-rhdcc.gc.ca>:

Hi,

First of all, thx for your work.

Question:

I was validating the following site with your online tools
and the results were different with the WAVE Evaluation Tool version 3.1.3 add-on in Firefox 80.0.1(64 bit)

https://wave.webaim.org/report#/https://www.statcan.gc.ca/fra/consultation/question-fra

The add-on reported
18 Errors

    17 X Missing form label
        Missing form label 1Missing form label 2Missing form label 3Missing form label 4Missing form label 5Missing form label 6Missing form label 7Missing form label 8Missing form label 9Missing form label 10Missing form label 11Missing form label 12Missing form label 13Missing form label 14Missing form label 15Missing form label 16Missing form label 17More information
    1 X Empty heading
        Empty heading 1More information

https://blog.pope.tech/2020/02/28/missing-form-label-search/

Is there a reason for that ?

Also You have 1 contrast error in this page

https://wave.webaim.org/report#/https://webaim.org/contact/

**Comment by shawnthompson** [comment]
This is interesting, might want to reply to Jared and ask him to put a disclaimer that...

> JavaScript-enabled content may not be loaded in pages when viewed in our online service.

Thanks for letting me know. 

I sent you and email to your work email to catch up. 

Stay safe!
